Repository shikha-16/Women-in-Technology, pull requests merged in 2021-10, with the labels that each got.

#157 Corrected navbar
  website/src/components/Header/Header.js
Labels: hacktoberfest-accepted

#159 Add events and its link to the readme and event page
  README.md
  website/src/pages/events.js
Labels: hacktoberfest, hacktoberfest-accepted

#167 Made Guidelines Page Responsive
  website/src/components/Contributing/ss.css
Labels: hacktoberfest-accepted

#148 #131 changed links to open in new tab
  documents/Changes/UnusedImports.txt
  documents/Changes/after fixing links.png
  documents/Changes/after margin-bottom.png
  documents/Changes/before fixing links.png
  documents/Changes/before margin-bottom.png
  website/src/App.js
  website/src/DarkMode.css
  website/src/components/Articles/Articles.js
  website/src/components/BeginnersLinks/BeginnersLinks.js
  website/src/components/Card/index.js
  website/src/components/CarouselCards/index.js
  website/src/components/CarouselComponent/CarouselComponent.js
  website/src/components/CarouselComponent/carousel.css
  website/src/components/Community/Contributors/ContributorsComponent.js
  website/src/components/Community/Contributors/MemberComponent.js
  website/src/components/Community/Contributors/Tests.css
  website/src/components/ComputerScienceSection/index.js
  website/src/components/Contributing/ss.css
  website/src/components/Footer/Footer.css
  website/src/components/Footer/Footer.js
  website/src/components/Github/Githubcomponent.js
  website/src/components/Header/Header.js
  website/src/components/Inspirational/Inspirational.js
  website/src/components/Layout.js
  website/src/components/Organization/organizationComponent.js
  website/src/components/Resources/resourcesComponent.js
  website/src/components/Scholarships/ScholarshipComponent.js
  website/src/data/contributing.js
  website/src/data/organization.js
  website/src/helpers/textToLink.js
  website/src/pages/articles.js
  website/src/pages/contributing.js
  website/src/pages/events.js
  website/src/pages/github.js
  website/src/pages/infographics.js
  website/src/pages/inspirations.js
  website/src/pages/organization.js
  website/src/pages/scholarship.js
Labels: hacktoberfest-accepted

#171 Fixes issue #140
  website/src/App.js
  website/src/components/Contributing/Contributing.js
  website/src/components/Header/Header.js
  website/src/pages/beginners.js
Labels: hacktoberfest, hacktoberfest-accepted

#177 Issues resolved
  website/src/components/Scholarships/ScholarshipComponent.js
  website/src/pages/events.js
Labels: hacktoberfest

#193 fixes dak theme in community pag
  website/package.json
  website/src/components/Community/Contributors/ContributorsComponent.js
  website/src/components/Community/Contributors/MemberComponent.js
  website/src/components/Community/Contributors/Tests.css
  website/src/components/Founder/Founder.css
  website/src/components/Founder/FounderComponent.js
  website/src/pages/infocard.css
Labels: hacktoberfest, hacktoberfest-accepted

#199 addes new community
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#198 remove lines
  website/src/components/Founder/Founder.css
Labels: hacktoberfest, hacktoberfest-accepted
